### ISSUE TITLE
Can you please let me know when will the code available?

### ISSUE THREAD

**Issue by skbhat** [ZX-Yin/ms-nerf#1]

**Comment by ZX-Yin** [comment]
Thank you for your interest. We will release the original training and testing code of Mip-NeRF 360 based experiments within 24 hours. Sorry for the delay.

**Comment by ZX-Yin** [comment]
We have released the training and evaluating code for Mip-NeRF 360 exp, and we are working to integrate the Mip-NeRF and NeRF exp into this repo. I'll close this issue, please feel free to open another issue if you have any question : )

**Comment by skbhat** [comment]
Thanks a lot for the quick response.
