### ISSUE TITLE
[Environment] Cannot find compatible jax and jaxlib

### ISSUE THREAD

**Issue by voldenuit-yanagi** [ZX-Yin/ms-nerf#2]
Ubuntu 22.04 (Windows 11 WSL)
Cuda 11.8    Cudnn 8.6.0.163
jax+jaxlib 0.4.14

When I configured the environment using `pip install -r requirements.txt`, I got the error 
`ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.24+cuda11.cudnn82 (from jax[cuda11-cudnn82]) (from versions: 0.4.13)
ERROR: No matching distribution found for jaxlib==0.3.24+cuda11.cudnn82`

Then I tried to use `pip install --upgrade "jax[cuda11_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` as mentioned in the [install guide of jax](https://github.com/google/jax#installation), but when I ran the unit tests script, I got the error `ImportError: cannot import name 'ShapedArray' from 'jax' (/home/xxx/anaconda3/envs/ms-nerf/lib/python3.9/site-packages/jax/__init__.py)`.

How do I fix this? Thanks a lot!

**Comment by voldenuit-yanagi** [comment]
I found similar jax version problems with Windows system in the [issues of mutinerf](https://github.com/google-research/multinerf/issues?q=is%3Aissue), so I tried to use WSL to configure environment and succeeded!

Reference for someone having similar problems with me: configure with WSL and use`pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` instead of 'jax[cuda11_cudnn82]==0.3.24 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html' in requirenments.txt

**Comment by ZX-Yin** [comment]
Thank you for your interest!

I have tested the code on two platforms: Ubuntu 20.04.6 LTS Cuda 11.8 Cudnn 8.4.1 RTX 3090*2 and 20.04.4 LTS Cuda 11.4 Cudnn 8.4.1 V100*8. They all work for me. 
The command line for installing Jax is the the way recommended last year from their official repo, and it may have some changes. Perhaps you could try to download the package from [this website](https://storage.googleapis.com/jax-releases/jax_cuda_releases.html) and install it manually?
![image](https://github.com/ZX-Yin/ms-nerf/assets/45428704/468902d8-c15c-4f4e-9117-acacfb214a20)

Good luck.

**Comment by ZX-Yin** [comment]
I will close this issuse. Please feel free to open another issue if you still have any question.
